project/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import book, admin, account, user, bill, order

urlpatterns = [
    # path('admin/', admin.site.urls),
    # 书籍信息管理
    path('book/list/', book.book_list),
    path('book/add/', book.book_add),
    path('book/<int:nid>/edit/', book.book_edit),
    path('book/<int:nid>/delete/', book.book_delete),
    path('book/<int:nid>/sale/', book.book_sale),

    # 管理员用户管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 账户: 登录与注销
    path('', book.book_list),
    path('login/', account.login),
    path('logout/', account.logout),

    # 用户编辑自身信息
    path('user/<int:nid>/edit/', user.user_edit),

    # 账单管理
    path('bill/list/', bill.bill_list),
    path('bill/add/', bill.bill_add),
    path('bill/<int:nid>/delete/', bill.bill_delete),
    path('bill/history/', bill.financial_history),

    # 图书进货: 订单管理
    path('order/list/', order.order_list),  # 列表
    path('order/add/', order.order_add),  # 添加
    path('order/<int:nid>/pay/', order.order_pay),  # 支付
    path('order/<int:nid>/cancel/', order.order_cancel),  # 取消订单: 针对未付款书籍
    path('order/<int:nid>/delete/', order.order_delete),  # 删除订单：针对已付款书籍

]

app01/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator


# Create your models here.

class BookInfo(models.Model):
    isbn = models.CharField(verbose_name="ISBN", max_length=13, unique=True)
    name = models.CharField(verbose_name="书名", max_length=50)
    press = models.CharField(verbose_name="出版社", max_length=30, null=True, blank=True)
    author = models.CharField(verbose_name="作者", max_length=60, null=True, blank=True)
    retail_price = models.DecimalField(verbose_name="零售价格", max_digits=10, decimal_places=2, default=0)
    amount = models.IntegerField(verbose_name="库存数量", default=0)


class Admin(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    employee_id = models.CharField(verbose_name='工号', max_length=11, unique=True)
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    # 在django中做的约束 建立映射关系
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)
    group_choices = (
        (1, "超级管理员"),
        (2, "普通管理员"),
    )
    group = models.SmallIntegerField(verbose_name='用户组', choices=group_choices)


class SystemBalance(models.Model):
    # 系统账号余额
    balance = models.DecimalField(max_digits=18, decimal_places=2, default=0)


class Bill(models.Model):
    type_choices = (
        (1, '收入'),
        (2, '支出')
    )

    timestamp = models.DateTimeField(verbose_name='时间', default=timezone.now().strftime("%Y-%m-%d %H:%M:%S"))
    username = models.ForeignKey(verbose_name='操作用户', to='Admin', to_field='username', null=True, blank=True,
                                 on_delete=models.SET_NULL, db_column='username')
    # 在 Django 的 ORM 中ForeignKey默认会使用对应模型的主键作为关联字段
    # 因此在数据库中对应的列属性为整型数字（即该模型的主键类型）。还会加上_id标识
    # 会关联的是对象！而不是字段
    # 如果外键使用时，在数据库中使用其他类型的列属性，可以使用模型中的db_column选项来指定具体的列名
    type = models.SmallIntegerField(verbose_name='类型', choices=type_choices)
    amount = models.DecimalField(verbose_name='金额', max_digits=16, decimal_places=2)
    description = models.CharField(verbose_name='备注', max_length=128, null=True, blank=True)


class Order(models.Model):
    timestamp = models.DateTimeField(verbose_name='创建时间', default=timezone.now().strftime("%Y-%m-%d %H:%M:%S"))
    username = models.ForeignKey(verbose_name='操作用户', to='Admin', to_field='username', null=True, blank=True,
                                 on_delete=models.SET_NULL, db_column='username')
    isbn = models.CharField(verbose_name="ISBN", max_length=13)
    purchase_price = models.DecimalField(verbose_name="进货价格", max_digits=8, decimal_places=2, default=0,
                                         validators=[MinValueValidator(0)])
    purchase_amount = models.PositiveIntegerField(verbose_name="进货数量")
    total = models.DecimalField(verbose_name='总金额', max_digits=12, decimal_places=2, default=0)
    state_choice = ((1, '未支付'), (2, '已支付'), (3, '已取消'))
    state = models.SmallIntegerField(verbose_name='订单状态', choices=state_choice, default=1)

    def save(self, *args, **kwargs):
        # 在模型保存时会自动计算这个属性
        self.total = (self.purchase_price * self.purchase_amount)
        super(Order, self).save(*args, **kwargs)

app01/views.py
from django.shortcuts import render, redirect
from django.core.validators import RegexValidator, ValidationError
from app01 import models
from django import forms
from django.db.models import Q
from app01.utils.pagination import Pagination
from app01.utils.form import *


def book_list(request):
    search_data = request.GET.get('query', '')
    if search_data:
        queryset = models.BookInfo.objects.filter(
            Q(isbn__contains=search_data) | Q(name__contains=search_data) | Q(author__contains=search_data)) \
            .order_by('name')
    else:
        queryset = models.BookInfo.objects.all().order_by('name')
    page_object = Pagination(request, queryset, page_size=8)
    context = {
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html(),  # 生成页码
        "search_data": search_data,
    }
    return render(request, 'book_list.html', context)


def book_add(request):
    '''
    待完善
    这个函数用户初始化书籍信息，可以定义库存
    我希望初始化时候定义的库存可以加入到进出货账单上去，便于最后记录
    :param request:
    :return:
    '''
    if request.method == 'GET':
        form = BookInfoModelForm()
        return render(request, 'book_add.html', {'form': form})
    else:
        form = BookInfoModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/book/list/')
        else:
            return render(request, 'book_add.html', {'form': form})


def book_edit(request, nid):
    row_object = models.BookInfo.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = BookEditInfoModelForm(instance=row_object)
        # 使用instance属性，这种方式可以实现填写默认值，相当于把value属性全部设置。还有一个功能是能找到更新的位置
        return render(request, 'book_edit.html', {'form': form})
    else:
        form = BookEditInfoModelForm(data=request.POST, instance=row_object)
        if form.is_valid():
            form.save()
            return redirect('/book/list/')
        else:
            return render(request, 'book_edit.html', {'form': form})


def book_delete(request, nid):
    models.BookInfo.objects.filter(id=nid).delete()
    return redirect('/book/list/')


def book_sale(request, nid):
    pass

app01/views/account.py
from django.shortcuts import render, redirect
from django.core.validators import RegexValidator, ValidationError
from app01 import models
from django import forms
from django.db.models import Q
from app01.utils.pagination import Pagination
from app01.utils.form import *


def login(request):
    """ 登录 """
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    # POST提交
    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 表单有效，需要后端自行检查用户名密码是否正确(是否存在于数据库)
        #  cleaned_data : {'username': 'wupeiqi', 'password': '5e5c3bad7eb35cba3638e145c830c35f'}
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()  # 去数据库找这条数据
        if not admin_object:
            form.add_error("password", "用户名或密码错误")
            # form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中,其同时作为键，把相应数据存储到后端的session中
        request.session["info"] = {'id': admin_object.id, 'username': admin_object.username,'group':admin_object.group}
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect("/book/list/")

    # 若输入表单无效，form携带错误信息返回登录页面
    return render(request, 'login.html', {'form': form})


def logout(request):
    request.session.clear()  # 清除session中的信息 下次登录cookie无法找到有效session，必须重新登录
    return redirect('/login/')  # 退出到登录页面

app01/views/admin.py
from django.shortcuts import render, redirect
from django.core.validators import RegexValidator, ValidationError
from app01 import models
from django import forms
from django.db.models import Q
from app01.utils.pagination import Pagination
from app01.utils.form import *


def admin_list(request):
    queryset = models.Admin.objects.all().order_by('group')
    page_object = Pagination(request, queryset, page_size=8)
    context = {
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html()  # 生成页码
    }
    return render(request, 'admin_list.html', context)


def admin_add(request):
    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'change.html', {'form': form, 'title': '新建管理员'})
    else:  # POST
        form = AdminModelForm(data=request.POST)
        if form.is_valid():
            # 如果有错，信息不能存储，自然无效
            form.save()
            return redirect('/admin/list/')
        else:
            return render(request, 'change.html', {'form': form, 'title': '新建管理员'})


def admin_delete(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')


def admin_edit(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()  # 默认列表，只有取first才可以取出对象
    if not row_object:
        # 存在性检查时为了防止并发操作
        return render(request, 'error.html', {'error_msg': '该数据不存在'})

    title = '编辑管理员'
    if request.method == 'GET':
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change.html', {'form': form, 'title': title})
    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list')
    else:
        return render(request, 'change.html', {'form': form, 'title': title})


def admin_reset(request, nid):
    # 重置密码

    row_object = models.Admin.objects.filter(id=nid).first()
    title = "重置密码 用户: {}".format(row_object.username)
    if not row_object:
        return render(request, 'error.html', {'error_msg': '操作的对象不存在'})
    if request.method == 'GET':
        form = AdminResetModelForm()  # 不输入instance 不能查看原有密码
        return render(request, 'change.html', {'form': form, 'title': title})
    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    else:
        return render(request, 'change.html', {'form': form, 'title': title})

app01/views/bill.py
from django.shortcuts import render, redirect
from django.core.validators import RegexValidator, ValidationError
from app01 import models
from django import forms
from django.db.models import Q
from app01.utils.pagination import Pagination
from app01.utils.form import *
import datetime


def bill_list(request):
    queryset = models.Bill.objects.all().order_by('-timestamp')
    page_object = Pagination(request, queryset, page_size=8)
    balance_obj = models.SystemBalance.objects.first()
    if balance_obj:
        balance = balance_obj.balance
    else:
        balance = '--'
    context = {
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html(),  # 生成页码
        'balance': balance,
    }
    return render(request, 'bill_list.html', context)


def bill_add(request):
    if request.method == 'GET':
        form = BillModelForm()
        return render(request, 'change.html', {'form': form, 'title': '新建账单'})
    else:  # POST
        form = BillModelForm(data=request.POST)
        balance_object = models.SystemBalance.objects.first()
        if not balance_object:
            models.SystemBalance.objects.create(balance=0)
            balance_object = models.SystemBalance.objects.first()
        if form.is_valid():
            # 如果有效
            # 时间会自动加，需要附加上用户名
            info_dict = request.session.get('info')  # 获取当前用户名
            admin = models.Admin.objects.get(username=info_dict['username'])
            bill = form.save(commit=False)
            bill.username = admin  # 外键必须关联到一个对象!
            bill.save()
            balance_object.balance += form.cleaned_data['amount']
            balance_object.save()
            return redirect('/bill/list/')
        else:
            # 错误信息附加
            return render(request, 'change.html', {'form': form, 'title': '新建账单'})


def bill_delete(request, nid):
    models.Bill.objects.filter(id=nid).delete()
    return redirect('/bill/list/')


def parse_period(period):
    """
    用于将period中的日期分割为起、止时间, 截止时间默认为当前
    """
    if '~' in period:
        start_date, end_date = period.split('~')
    else:
        start_date = period
        end_date = datetime.date.today()
    start_date = datetime.datetime.strptime(str(start_date), '%Y-%m-%d')  # 参数需为字符串
    end_date = datetime.datetime.strptime(str(end_date), '%Y-%m-%d')
    return start_date, end_date


def financial_history(request):
    """
    period: 时间段,如'2020-01'(至今), '2020-05-01~2020-05-31'
    income_expense: 收入/支出,1表示收入,2表示支出,0表示总收益
    """
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    income_expense = request.GET.get('income_expense')
    if not (start_date and end_date and income_expense):
        return render(request, 'financial_history.html')
    start_date = datetime.datetime.strptime(start_date, '%Y-%m-%d')
    end_date = datetime.datetime.strptime(end_date, '%Y-%m-%d')
    start_date = datetime.datetime.combine(start_date, datetime.time.min)
    end_date = datetime.datetime.combine(end_date, datetime.time.max)
    queryset=models.Bill.objects.filter(timestamp__range=(start_date,end_date))
    total_amount=0
    type_display='总收益'
    if int(income_expense)==1:
        queryset=queryset.filter(type=1)
        type_display='收入'
    if int(income_expense)==2:
        queryset=queryset.filter(type=2)
        type_display='支出'
    for bill in queryset:
        total_amount+=bill.amount
    context={
        'bills':queryset,
        'total_amount':total_amount,
        'period':start_date.strftime('%Y-%m-%d')+'~'+end_date.strftime('%Y-%m-%d'),
        'income_expense':type_display
    }
    return render(request, 'financial_history.html', context)

app01/views/password_generate.py
import hashlib
password='123'
obj = hashlib.md5('django-insecure-n+^bx-lug#!un_42-w#9y*sxof^)_5$jnqu!##4qf5^#tdk%16'.encode('utf-8'))
obj.update(password.encode('utf-8'))
print(obj.hexdigest())

app01/views/user.py
from django.shortcuts import render, redirect
from django.core.validators import RegexValidator, ValidationError
from app01 import models
from django import forms
from django.db.models import Q
from app01.utils.pagination import Pagination
from app01.utils.form import *


#  编辑自己的个人信息的入口(不能编辑别人) 为更新自己的session信息,编辑后需要重新登录
def user_edit(request, nid):
    row_object = models.Admin.objects.filter(id=nid).first()  # 默认列表，只有取first才可以取出对象
    if not row_object:
        # 存在性检查时为了防止并发操作
        return render(request, 'error.html', {'error_msg': '该数据不存在'})
    if request.method == 'GET':
        form = UserEditModelForm(instance=row_object)
        return render(request, 'user_edit.html', {'form': form})
    form = UserEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/logout/')
    else:
        return render(request, 'user_edit.html', {'form': form})

app01/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-primary" href="/admin/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建管理员
            </a>
            <!-- target = '_blank' 可以新页面打开-->
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">管理员列表</div>

            <!-- Table -->
            <table class="table">
                <thead>
                <tr>
                    <th>用户组</th>
                    <th>工号</th>
                    <th>用户名</th>
                    <th>姓名</th>
                    <th>年龄</th>
                    <th>性别</th>
                    <th>密码</th>
                    <th>操作</th>

                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.get_group_display }}</td>
                        <td>{{ obj.employee_id }}</td>
                        <td>{{ obj.username }}</td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.get_gender_display }}</td>
                        <td>******</td>
                        <td>
                            <a class="btn btn-info btn-xs" href='/admin/{{ obj.id }}/edit/'>编辑</a>
                            <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete">删除</a>
                            <a class="btn btn-warning btn-xs" href='/admin/{{ obj.id }}/reset/'>密码重置</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div style="text-align: center">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

app01/templates/bill_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-primary" href="/bill/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建额外账单
            </a>
            <a class="btn btn-primary" href="/bill/history/">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                查看指定时间段账单
            </a>
            <!-- target = '_blank' 可以新页面打开-->
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">账单列表</div>

            <!-- Table -->
            <table class="table">
                <thead>
                <tr>
                    <th style="width: 200px;">时间</th>
                    <th>用户</th>
                    <th>类型</th>
                    <th>金额 ¥</th>
                    <th style="width: 280px;">备注</th>
                    <th>操作</th>

                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.timestamp|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ obj.username.username }}</td>
                        <td>{{ obj.get_type_display }}</td>
                        <td>{{ obj.amount }}</td>
                        <td>{{ obj.description }}</td>
                        <td>
                            <a class="btn btn-danger btn-xs" href="/bill/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            账户余额: {{ balance }}
        </div>
        <div style="text-align: center">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

app01/templates/book_add.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">新建书籍信息</h1>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate> <!-- novalidate 不启动浏览器校验-->
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span style="color: red">{{ field.errors.0 }}</span> <!-- 取首个错误信息 -->
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提交</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

app01/templates/book_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">编辑书籍信息</h3>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate> <!-- novalidate 不启动浏览器校验-->
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span style="color: red">{{ field.errors.0 }}</span> <!-- 取首个错误信息 -->
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

app01/templates/book_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <div class="row">
                <div class="col-md-4">
                    <a class="btn btn-primary" href="/book/add/">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                        新建书籍信息
                    </a> <!-- 使用 target = '_blank' 可以在新页面打开-->
                </div>
                <div class="col-md-4 col-md-offset-4">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="ISBN/书名/作者" name="query"
                                   value="{{ search_data }}">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                        </div><!-- /input-group -->
                    </form>
                </div>
            </div>
        </div>


        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                书籍信息列表
            </div>

            <!-- Table -->
            <table class="table">
                <thead>
                <tr>
                    <th>ISBN</th>
                    <th>书名</th>
                    <th>出版社</th>
                    <th>作者</th>
                    <th>零售价格</th>
                    <th>库存量</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.isbn }}</td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.press }}</td>
                        <td>{{ obj.author }}</td>
                        <td>{{ obj.retail_price }}</td>
                        <td>{{ obj.amount }}</td>
                        <td>
                            <a class="btn btn-success btn-xs" href='/book/{{ obj.id }}/sale/'>出售</a>
                            <a class="btn btn-info btn-xs" href='/book/{{ obj.id }}/edit/'>编辑</a>
                            <a class="btn btn-danger btn-xs" href="/book/{{ obj.id }}/delete">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div style="text-align: center">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}

app01/templates/change.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ title }}</h3>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate> <!-- novalidate 不启动浏览器校验-->
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span style="color: red">{{ field.errors.0 }}</span> <!-- 取首个错误信息 -->
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提交</button>
                        <a href="/book/list/" class="btn btn-warning">放弃修改</a>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

app01/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ error_msg }}
</body>
</html>

app01/templates/financial_history.html
{% extends 'layout.html' %}

{% block content %}
<h1>财务记录</h1>
<form method="GET" class="text-center">
    <label>起始日期: 
        <input type="date" name="start_date" class="form-control" max="today" > 
    </label>
    <label>结束日期: 
        <input type="date" name="end_date" class="form-control" value="today" max="today" > 
    </label>
    <br>
    <label>收入/支出:
        <input type="radio" name="income_expense" value=1 class="form-check-input" autocomplete="off"> 收入  
        <input type="radio" name="income_expense" value=2 class="form-check-input" autocomplete="off"> 支出
        <input type="radio" name="income_expense" value=0 class="form-check-input" autocomplete="off"> 总收益
    </label>
    <button type="submit">查询</button>
</form>
<h2>{{ period }} {{ income_expense }}</h2>
<p>总额:¥{{ total_amount }}</p>
<table class="table table-striped table-bordered">
    <thead class="thead-light">
    <tr>
        <th>记账时间</th>
        <th>操作用户</th>
        <th>收入/支出</th>
        <th>金额(¥)</th>
        <th>备注</th>
    </tr>
    </thead>
    <tbody  class="table-light">
    {% for bill in bills %}
        <tr>
            <td>{{ bill.timestamp}}</td>
            <td>{{ bill.username.username}}</td>
            <td>{% if bill.type == 1 %}
                <span class="badge badge-success">收入</span>
                {% elif bill.type == 2 %} 
                <span class="badge badge-danger">支出</span>
                {% endif %}</td>
            <td>{{ bill.amount }}</td>
            <td>{{ bill.description }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

app01/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-primary" href="/order/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建进货订单
            </a>
            <!-- target = '_blank' 可以新页面打开-->
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">订单列表</div>

            <!-- Table -->
            <table class="table">
                <thead>
                <tr>
                    <th>创建时间</th>
                    <th>操作用户</th>
                    <th>ISBN</th>
                    <th>进货数量</th>
                    <th>进货价格 ¥</th>
                    <th>总金额 ¥</th>
                    <th>订单状态</th>
                    <th>操作</th>

                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.timestamp|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ obj.username.username }}</td>
                        <td>{{ obj.isbn }}</td>
                        <td>{{ obj.purchase_amount }}</td>
                        <td>{{ obj.purchase_price }}</td>
                        <td>{{ obj.total }}</td>
                        <td>{{ obj.get_state_display }}</td>
                        <td>
                            {% if obj.state == 1 %}
                                <a class="btn btn-primary btn-xs" href="/order/{{ obj.id }}/pay/">支付订单</a>
                                <a class="btn btn-warning btn-xs" href="/order/{{ obj.id }}/cancel/">取消订单</a>
                            {% endif %}
                            {% if obj.state == 2 or obj.state == 3 %}
                                <a class="btn btn-danger btn-xs" href="/order/{{ obj.id }}/delete/">删除订单</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div style="text-align: center">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>
    </div>
{% endblock %}